### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by HashmatShadab** [hyperevolnet/Terminator#1]
Hi! Thanks for sharing your work.
Will the code be released anytime soon?

**Comment by Karn3003** [comment]
Looking forward for the open-source codebase. Btw cool work.

**Comment by ex3ndr** [comment]
Why this even could be a question to release or not? It is just resnet, not something crazy

**Comment by hyperevolnet** [comment]
> Why this even could be a question to release or not? It is just resnet, not something crazy

For the first question, there are many reasons. The current version does not have any crazy results you think.

**Comment by mileseverett** [comment]
If you're not going to release the code, your method will fade into obscurity and have no impact.

**Comment by hyperevolnet** [comment]
> If you're not going to release the code, your method will fade into obscurity and have no impact.

Thanks your suggestions.

**Comment by hyperevolnet** [comment]
Hi I am updating code, and I think you can take a look at the released code first.
